platform: "mvne"

workflows:
  release: ["deploy_java"]

stages:
  deploy_java: ["mvn -f src/java-xconfig deploy"]

plugins:
  versioning:
    get_version: "mvn -f src/java-xconfig -q com.tuenti.maven.plugins:tuentiversions-maven-plugin:show-current"
    set_current_release_version: "mvn -f src/java-xconfig com.tuenti.maven.plugins:tuentiversions-maven-plugin:set-release"
    set_next_development_version: "mvn -f src/java-xconfig com.tuenti.maven.plugins:tuentiversions-maven-plugin:set-next-devel"
