platform: "mvne"

workflows:
  release_java: ["deploy_java", "package_java"]
  package_java: ["package_java"]
  deploy_java_utils: ["deploy_java_utils"]

stages:
  deploy_java: ["mvn -f src/java-xconfig deploy"]
  package_java: ["cd src/java-xconfig; ./makePackage.sh"]
  deploy_java_utils: ["mvn -f src/xconfig-java-utils deploy"]

plugins:
  artifacts:
    include: ["source/src/java-xconfig/*.deb"]
  versioning:
    get_version: "mvn -f src/java-xconfig -q com.tuenti.maven.plugins:tuentiversions-maven-plugin:show-current"
    set_current_release_version: "mvn -f src/java-xconfig com.tuenti.maven.plugins:tuentiversions-maven-plugin:set-release"
    set_next_development_version: "mvn -f src/java-xconfig com.tuenti.maven.plugins:tuentiversions-maven-plugin:set-next-devel"
