version: '2'
services:
  builder:
    image: "docker.tuenti.io/service-inf/java-builder:2.5"
    volumes:
      - "./:/source"

  php-builder:
    image: "docker.tuenti.io/service-inf/php-builder:7.0.19"
    volumes:
      - "./:/source"
