version: '2'
services:
  java-builder:
    image: "docker.tuenti.io/service-inf/java8-maven:5.0"
    volumes:
      - "./:/source"
    environment:
      - DEBIAN_FRONTEND=noninteractive

  buster-builder:
    image: "docker.tuenti.io/debian:buster-tuenti3"
    command: "sleep infinity"
    volumes:
      - "./:/source"
