version: '2'
services:
  builder:
    image: "docker.tuenti.io/service-inf/java-builder:2.5"
    volumes:
      - "./:/source"

  xconfig-builder:
    image: "docker.tuenti.io/debian:stretch"
    command: "sleep infinity"
    volumes:
      - "./:/source"
