version: '2'
services:
  java-builder:
    image: "docker.tuenti.io/service-inf/java8-maven:5.0"
    volumes:
      - "./:/source"
    environment:
      - DEBIAN_FRONTEND=noninteractive

  buster-builder:
    image: "docker.tuenti.io/debian:buster-tuenti6"
    command: "sleep infinity"
    volumes:
      - "./:/source"
      - "~/.pypirc:/root/.pypirc"

  bullseye-builder:
    image: "debian:bullseye"
    command: "sleep infinity"
    volumes:
      - "./:/source"
      - "~/.pypirc:/root/.pypirc"
