#!/bin/bash

set -o errexit nounset

source /etc/os-release
if [ "$ID" != "debian" ] ; then
    echo "Not supported operating system"
    exit 1;
fi
sed "s/DISTRIBUTIONNAME/~$VERSION_CODENAME/g" debian/changelog.template > debian/changelog

if ! command -v wget >/dev/null ; then
    apt-get update; apt-get install -y wget
fi

# phpize needs sed available at /usr/bin/sed
if [ ! -f /usr/bin/sed ]; then
    ln -s /bin/sed /usr/bin/sed
fi

wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $VERSION_CODENAME main" > /etc/apt/sources.list.d/php.list

apt-get update; apt-get install -y build-essential devscripts php7.4-dev php7.4
mk-build-deps -i -t "apt-get -y"
