testConfig:
  deletedKey: !delete
  overridedKey:
    b: 42
  sampleExpandString: !expandstring ['this is an expanded %1', [testConfig, sampleString]]
  sampleExpandRef: !expandref [testConfig, sampleInt]
  sampleExpandEnv: !expandenv SAMPLE_ENV
